### ISSUE TITLE
[question] How do you find the ID / name of things?

### ISSUE THREAD

**Issue by Sonata26** [YimMenu-Lua/Alestarov-Menu#5]
How do you find the ID / name of things? For example, I would like to change the Cayo heist target from the panther statue to a pink diamond but I don't know the id of either one. Or where the stat names come from like: `MPPLY_TOTAL_EVC`.

Thank you for making these scripts, they've been helpful in learning to make YimMenu scripts, and I would appreciate a little guidance on how to find the entity names / any magic numbers if you don't mind. 😅 

Edit: Upon closer inspection, I see the heist target is just an integer and `3` is the diamond. Still it would be nice to know where `"H4CNF_TARGET"` comes from. There is also the issue of secondary targets not working when you loot them.

**Comment by xesdoog** [comment]
@Sonata26 If you want to learn, [unknowncheats forum](https://www.unknowncheats.me/forum/grand-theft-auto-v/) is a great source of information gathered by members of the community.

- [**Packed Stats**](https://www.unknowncheats.me/forum/grand-theft-auto-v/578963-packed-stats-int-bool-collection-thread.html)
- [**Globals and locals**](https://www.unknowncheats.me/forum/grand-theft-auto-v/500059-globals-locals-discussion-read-page-1-a.html)
- [**Structs & offsets**](https://www.unknowncheats.me/forum/grand-theft-auto-v/144028-grand-theft-auto-reversal-structs-offsets.html)

You can also check these [decompiled scripts](https://github.com/root-cause/v-decompiled-scripts/).

**Comment by Sonata26** [comment]
> @Sonata26 If you want to learn, [unknowncheats forum](https://www.unknowncheats.me/forum/grand-theft-auto-v/) is a great source of information gathered by members of the community.
> 
>     * [**Packed Stats**](https://www.unknowncheats.me/forum/grand-theft-auto-v/578963-packed-stats-int-bool-collection-thread.html)
> 
>     * [**Globals and locals**](https://www.unknowncheats.me/forum/grand-theft-auto-v/500059-globals-locals-discussion-read-page-1-a.html)
> 
>     * [**Structs & offsets**](https://www.unknowncheats.me/forum/grand-theft-auto-v/144028-grand-theft-auto-reversal-structs-offsets.html)
> 
> 
> You can also check these [decompiled scripts](https://github.com/root-cause/v-decompiled-scripts/).

Thanks
